name: Stable build

on:
  pull_request:
    branches:
      - main
    paths:
      - images/custom/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env
      - .github/workflows/build_stable.yml

  push:
    branches:
      - main
    paths:
      - images/custom/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env

  # Triggered from frappe/frappe and frappe/erpnext on releases
  repository_dispatch:

  workflow_dispatch:

jobs:
  v14:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      repo: erpnext
      version: "14"
      push: ${{ github.repository == 'geniusdynamics/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.10.13
      node_version: 16.20.2
      file_path: ./apps.json
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  v15:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      repo: erpnext
      version: "15"
      push: ${{ github.repository == 'geniusdynamics/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.11.6
      node_version: 18.18.2
      file_path: ./apps.json
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  update_versions:
    name: Update example.env and pwd.yml
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'geniusdynamics/frappe_docker' && github.event_name != 'pull_request' }}
    needs: v15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get latest versions
        run: python3 ./.github/scripts/get_latest_tags.py --repo erpnext --version 15

      - name: Update
        run: |
          python3 ./.github/scripts/update_example_env.py
          python3 ./.github/scripts/update_pwd.py

      - name: Push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add example.env pwd.yml
          if [ -z "$(git status --porcelain)" ]; then
            echo "versions did not change, exiting."
            exit 0
          else
            echo "version changed, pushing changes..."
            git commit -m "chore: Update example.env"
            git pull --rebase
            git push origin main
          fi

